# .air.toml
[build]
  cmd = "go build -o tmp/main ./cmd/evidenceverifier"
  bin = "tmp/main"
  full_bin = ""
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_ext = ["swp"]
  follow_symlink = true
  log = "build-errors.log"
  send_interrupt = true

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true
